### ISSUE TITLE
AOC-2023-D14-P2 - How does FindSequence work?

### ISSUE THREAD

**Issue by ChristopherHButler** [ShootMe/AdventOfCode#1]
Is there a name for your `FindSequence` algorithm I could look up? If not, would you mind explaining how / why your FindSequence method works for 2023 Day 14, Part 2 ?

**Comment by ShootMe** [comment]
It might have a name, but I'm not sure what it might be called. I just put together a basic check for 2 identical sequences in the passed in list starting from the end. I also start with at least a sequence length of 5 in this case to avoid any small sequences.

So if you had the following list passed in:
Vals: 1,2,3,4,5,6,1,2,3,4,5,6
Ind: 0,1,2,3,4,5,6,7,8,9,10,11
It starts i at ind 6 = val 1
since 1 != 6, i moves to 5
since 6 = 6 now, it then checks further down at both ends to make sure everything is the same
5 = 5
4 = 4
3 = 3
and so on, and since it finds the same sequence twice it returns the starting index and length

**Comment by ChristopherHButler** [comment]
Ahhh Thanks! I think I understand what you you did now. Can I also ask how you know that `loads[position + leftOver - 1] will give you the load you're looking for? Without some algorithm it feels a bit random to the untrained eye.

**Comment by ShootMe** [comment]
So at this point FindSequence has returned saying it found a duplicate sequence with a starting (position) and (length).
You then try to figure out what position in that sequence you would be at cycle 1000000000. This is just the modular math in the code. You then just do your current position + the remainder from the modular math.

The only reason for the -1 is that Im indexing from 0 instead of 1. You can avoid that by just using 999999999 instead, but I just opted to use 1000000000.

**Comment by ChristopherHButler** [comment]
Awesome thanks for taking to time to explain. Makes sense now :)

**Comment by ShootMe** [comment]
No problem, if you haven't already. the semi-official discord for AoC is a good place for code discussion as well :)
https://discord.gg/QbMbFhTdbW
